// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "NSAC App",
//   description: "Mission Control for Team Miracle",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="flex">
//         {/* Sidebar */}
//         <aside className="w-64 min-h-screen bg-[#0f172a] text-gray-300 flex flex-col p-6 sticky top-0">
//           <h1 className="text-xl font-bold text-white mb-8">🚀 Team Miracle</h1>
//           <nav className="flex flex-col gap-2">
//             {/* Active link */}
//             <a
//               href="src/app/page.tsx"
//               className="px-3 py-2 rounded-md bg-gray-800 text-white font-medium"
//             >
//               Dashboard
//             </a>

//             <a
//               href="#guide"
//               className="px-3 py-2 rounded-md hover:bg-gray-800 hover:text-white"
//             >
//               Navigation Guide
//             </a>

//             <a
//               href="#tools"
//               className="px-3 py-2 rounded-md hover:bg-gray-800 hover:text-white"
//             >
//               Tools we used
//             </a>

//             <a
//               href="#team"
//               className="px-3 py-2 rounded-md hover:bg-gray-800 hover:text-white"
//             >
//               Team
//             </a>
//           </nav>
//         </aside>

//         {/* Main content */}
//         <main
//   className="flex-1 min-h-screen bg-cover bg-center bg-no-repeat"
//   style={{ backgroundImage: "url('/Perseverance.jpg')" }}
// >
//   <div className="p-10">
//     {children}
//   </div>
// </main>

//         {/* <main className="flex-1 p-10 min-h-screen bg-cover bg-center bg-no-repeat bg-fixed" style={{ backgroundImage: "url('/Perseverance.jpg')" }}>{children}</main> */}
//       </body>
//     </html>
//   );
// }

"use client";

import { usePathname } from "next/navigation";
import { Plus_Jakarta_Sans } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); // current route

  // Helper function to apply active styles
  const navLinkClass = (href: string) =>
    `px-4 py-3 rounded-md font-medium ${
      pathname === href ? "bg-gray-800 text-white" : "hover:bg-gray-800 hover:text-white text-gray-300"
    }`;

  return (
    <html lang="en">
      <Head>
        <title>Team Miracle</title>
      </Head>
      <body className={`${plusJakartaSans.className} flex`}>
        {/* Sidebar */}
        <aside className="w-72 h-screen bg-[#0f172a] text-gray-300 flex flex-col p-6 fixed top-0 left-0">
          <h1 className="text-xl text-white mb-8">
            Team <b>Miracle</b> 🚀 <br /> NASA SAC — 2025
          </h1>

          <nav className="flex flex-col gap-6">
            <a href="/" className={navLinkClass("/")}>Dashboard</a>
            <a href="/guide" className={navLinkClass("/guide")}>Navigation Guide</a>
            <a href="/meda" className={navLinkClass("/meda")}>What is MEDA?</a>
            <a href="/tools" className={navLinkClass("/tools")}>Tools we used</a>
            <a href="/team" className={navLinkClass("/team")}>Team</a>
            <p className="text-sm py-6">
              Team Miracle, a student team from Chennai, uses data to make space missions smarter and achieve extraordinary results.
            </p>
          </nav>
        </aside>

        {/* Main Content */}
        <main
          className="flex-1 min-h-screen bg-cover bg-center bg-no-repeat bg-fixed ml-72"
          style={{ backgroundImage: "url('/Perseverance2.jpg')" }}
        >
          <div className="p-10">{children}</div>
        </main>
      </body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
